name: Build shadowsocks-rust

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - rust/Dockerfile

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Docker Build and Notify
        uses: vimagick/dockerfiles/.github/actions/docker-build-notify@master
        with:
          platforms: 'linux/amd64,linux/arm64,linux/arm/v7'
          context: 'rust'
          image_name: 'easypi/shadowsocks-rust'
          version_arg: 'SS_RUST_VERSION'
          version_value: '1.25.0'
